version: 2
updates:
  # 1. AKTUALIZACJA DOCKERA (Bardzo ważne dla bezpieczeństwa obrazu Alpine)
  - package-ecosystem: "docker"
    directory: "/vultron" # Ścieżka do folderu, gdzie jest Dockerfile
    schedule:
      interval: "weekly"

  # 2. AKTUALIZACJA PYTHONA (Zadziała tylko, gdy stworzysz plik requirements.txt)
  - package-ecosystem: "pip"
    directory: "/vultron"
    schedule:
      interval: "weekly"

  # 3. AKTUALIZACJA GITHUB ACTIONS (Skanery bezpieczeństwa itp.)
  - package-ecosystem: "github-actions"
    directory: "/" # Workflowy zawsze są w /.github/ wiec tu zostaje "/"
    schedule:
      interval: "weekly"
