services:
  vultron:
    build:
      context: ./vultron
    container_name: vultron
    restart: unless-stopped
    mem_limit: 2g

    networks:
      - ha-net

    environment:
      TZ: Europe/Warsaw
      HA_URL: http://homeassistant:8123/api
      HA_WS_URL: ws://homeassistant:8123/api/websocket

    secrets:
      - ha_token

    volumes:
      - ./data:/data:z
      - ~/vultron-test/ha-config/www:/config/www:z

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  ha_token:
    file: ./secrets/ha_token.txt

networks:
  ha-net:
    external: true