name: "Vultron"
description: "TotalnieNIEzaawansowana integracja z EduVulcan.pl (Oxgang)"
url: "https://github.com/htomasz/vultron"
version: "7.0.1"
slug: "vultron"
panel_icon: "mdi:school"
homeassistant: ">=2024.12.0"
issue_tracker: "https://github.com/htomasz/vultron/issues"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
homeassistant_api: true
full_access: false
map:
  - config:rw
options:
  username: ""
  password: ""
  log_level: "info"
  test_mode: false
schema:
  username: str
  password: password
  log_level: list(info|debug|trace)
  test_mode: bool
