name: Home Assistant Add-on Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Home Assistant Add-on Check
        uses: home-assistant/actions/hassio-addon-checker@master
        with:
          path: "./vultron"