name: "Skanowanie Bash (ShellCheck)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {} # <--- TO DODAJEMY, aby mieć przycisk "Run workflow"

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run ShellCheck
        id: run_shellcheck
        run: |
          # Znajdź wszystkie pliki .sh (omijając folder .git)
          FILES=$(find . -type f -name "*.sh" -not -path "*/.*")
          
          if [ -z "$FILES" ]; then
            echo "Brak plików .sh do przeskanowania."
            echo "created_report=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Uruchom shellcheck i zapisz wynik do pliku
          shellcheck -f sarif $FILES > shellcheck-results.sarif || true
          
          # Sprawdź czy plik nie jest pusty
          if [ -s shellcheck-results.sarif ]; then
            echo "created_report=true" >> $GITHUB_OUTPUT
          else
            echo "created_report=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v4
        if: steps.run_shellcheck.outputs.created_report == 'true'
        with:
          sarif_file: shellcheck-results.sarif
