name: Python Security Scan

on: [push, pull_request,workflow_dispatch]

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Install tools
        run: pip install bandit ruff

      - name: Run Bandit (Security Linter)
        # Dodaliśmy --skip B301, aby zignorować ostrzeżenia o pickle
        run: bandit -r . -ll -ii --skip B301
      - name: Run Ruff (Fast Linter)
        # Ignorujemy:
        # S301 (Pickle), S110 (except: pass), S112 (except: continue), S113 (requests timeout)
        run: ruff check . --select S --extend-ignore S301,S110,S112,S113