name: Python Security Scan

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: pip install bandit ruff

      - name: Run Bandit (Security Linter)
        # Dodaliśmy --skip B301, aby zignorować ostrzeżenia o pickle
        run: bandit -r . -ll -ii --skip B301
      - name: Run Ruff (Fast Linter)
        # --select S oznacza: sprawdzaj TYLKO Security. 
        # --extend-ignore S301: ignoruj Pickle.
        # Wszystkie błędy typu E401, E722 itp. zostaną teraz zignorowane.
        run: ruff check . --select S --extend-ignore S301