name: Container & Dependency Scan

on: [push, pull_request]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          # Wskazujemy folder z Twoim projektem
          scan-ref: 'vultron/'
          format: 'table'
          severity: 'CRITICAL,HIGH'